apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsera-nagios.fullname" . }}-auth
data:
  grafana_password: {{ .Values.GRAFANA_PASSWORD | b64enc }}
  nagios_password: {{ .Values.NAGIOS_PASSWORD | b64enc }}