apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.cronjob.namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: {{ .Values.cronjob.serviceAccountName }}
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ .Values.cronjob.imagePullSecret }}
          containers:
            - name: kubectl
              image: {{ .Values.cronjob.image }}
              imagePullPolicy: {{ .Values.cronjob.imagePullPolicy }}
              command:
                - kubectl
                - rollout
                - restart
                - -n
                - {{ .Values.cronjob.namespace }}
                - statefulset/{{ .Values.cronjob.deploymentToRestart }}

