import { Injectable } from '@nestjs/common';
import { ROLES, RoleName } from '../constants/roles';
import { PERMISSIONS, Permission } from '../constants/permissions';

@Injectable()
export class PermissionService {
  private readonly rolePermissions: Record<RoleName, Permission[]> = {
    [ROLES.UPGRADE_OPERATOR]: [
      PERMISSIONS.CLUSTER_VIEW,
      PERMISSIONS.UPGRADE_EXECUTE_NONPROD,
      PERMISSIONS.UPGRADE_VIEW,
      PERMISSIONS.UPGRADE_CANCEL,
      PERMISSIONS.HEALTH_VIEW,
      PERMISSIONS.BACKUP_VIEW,
      PERMISSIONS.SCHEDULE_VIEW,
      PERMISSIONS.CAMPAIGN_VIEW,
    ],
    [ROLES.SRE_ONCALL]: [
      PERMISSIONS.CLUSTER_VIEW,
      PERMISSIONS.UPGRADE_EXECUTE_NONPROD,
      PERMISSIONS.UPGRADE_VIEW,
      PERMISSIONS.UPGRADE_CANCEL,
      PERMISSIONS.HEALTH_VIEW,
      PERMISSIONS.REMEDIATION_APPROVE_NONDESTRUCTIVE,
      PERMISSIONS.BACKUP_VIEW,
      PERMISSIONS.SCHEDULE_VIEW,
      PERMISSIONS.CAMPAIGN_VIEW,
    ],
    [ROLES.CLUSTER_ADMIN]: [
      PERMISSIONS.CLUSTER_VIEW,
      PERMISSIONS.CLUSTER_REGISTER,
      PERMISSIONS.CLUSTER_UNREGISTER,
      PERMISSIONS.UPGRADE_EXECUTE_NONPROD,
      PERMISSIONS.UPGRADE_EXECUTE_PROD,
      PERMISSIONS.UPGRADE_VIEW,
      PERMISSIONS.UPGRADE_CANCEL,
      PERMISSIONS.UPGRADE_ROLLBACK,
      PERMISSIONS.HEALTH_VIEW,
      PERMISSIONS.REMEDIATION_APPROVE_NONDESTRUCTIVE,
      PERMISSIONS.BACKUP_MANAGE,
      PERMISSIONS.BACKUP_VIEW,
      PERMISSIONS.SCHEDULE_VIEW,
      PERMISSIONS.SCHEDULE_MANAGE,
      PERMISSIONS.CAMPAIGN_VIEW,
      PERMISSIONS.CAMPAIGN_MANAGE,
    ],
    [ROLES.CHANGE_COORDINATOR]: [
      PERMISSIONS.CLUSTER_VIEW,
      PERMISSIONS.UPGRADE_VIEW,
      PERMISSIONS.UPGRADE_EXECUTE_NONPROD,
      PERMISSIONS.UPGRADE_EXECUTE_PROD,
      PERMISSIONS.UPGRADE_CANCEL,
      PERMISSIONS.HEALTH_VIEW,
      PERMISSIONS.REMEDIATION_APPROVE_NONDESTRUCTIVE,
      PERMISSIONS.REMEDIATION_APPROVE_DESTRUCTIVE,
      PERMISSIONS.BACKUP_VIEW,
      PERMISSIONS.SCHEDULE_VIEW,
      PERMISSIONS.SCHEDULE_MANAGE,
      PERMISSIONS.CAMPAIGN_VIEW,
      PERMISSIONS.CAMPAIGN_MANAGE,
    ],
    [ROLES.COMPLIANCE_REVIEWER]: [
      PERMISSIONS.CLUSTER_VIEW,
      PERMISSIONS.UPGRADE_VIEW,
      PERMISSIONS.HEALTH_VIEW,
      PERMISSIONS.BACKUP_VIEW,
      PERMISSIONS.SCHEDULE_VIEW,
      PERMISSIONS.CAMPAIGN_VIEW,
      PERMISSIONS.AUDIT_VIEW,
      PERMISSIONS.AUDIT_EXPORT,
    ],
  };

  hasPermission(role: RoleName, permission: Permission): boolean {
    const permissions = this.rolePermissions[role];
    return permissions ? permissions.includes(permission) : false;
  }

  getPermissions(role: RoleName): Permission[] {
    return this.rolePermissions[role] ?? [];
  }

  isWriteOperation(method: string): boolean {
    return ['POST', 'PUT', 'PATCH', 'DELETE'].includes(method.toUpperCase());
  }
}
