apiVersion: v1
kind: ConfigMap
metadata:
  name: ch-initdb-config
data:
  ch-initdb.sql: |
    CREATE DATABASE IF NOT EXISTS kafka;
    CREATE DATABASE IF NOT EXISTS opseradb;

    -- Kafka Engine Table
    CREATE TABLE IF NOT EXISTS kafka.messages_queue ( message String)
    ENGINE = Kafka
    SETTINGS
    kafka_broker_list = '{{ .Values.KAFKA_BROKER_LIST }}',
    kafka_topic_list = '{{ .Values.KAFKA_TOPIC_LIST }}',
    kafka_group_name = '{{ .Values.CUSTOMER_NAME }}-ch-group',
    kafka_format= 'JSONAsString',
    kafka_max_block_size=1048576,
    kafka_row_delimiter = '\n',
    kafka_handle_error_mode = 'stream';

    -- KAFKA FINAL TABLE MERGETREE
    CREATE TABLE IF NOT EXISTS opseradb.messages
    (message String,
    _topic String,
    _key String,
    _offset UInt64,
    _partition UInt64,
    _timestamp DateTime,
    _error String,
    _raw_message String,
    etl_date Date DEFAULT toDate(now()),
    etl_ts DateTime DEFAULT now()
    ) ENGINE = MergeTree PARTITION BY toDate(_timestamp)
    ORDER BY (_topic, _timestamp)
    SETTINGS index_granularity = 8192 ;

    -- KAFKA MV CREATION TO PUSH CDC INTO FINAL TABLE
    CREATE MATERIALIZED VIEW kafka.messages_queue_mv
    TO opseradb.messages (`message` String, `_topic` String, `_key` String,
     `_offset` String, `_partition` String, `_timestamp` String, `_error` String, `_raw_message` String)
    AS SELECT message, _topic, _key, _offset, _partition, _timestamp, _error, _raw_message FROM kafka.messages_queue WHERE message LIKE '%{{ .Values.CUSTOMER_ID }}%';

    /*
    CREATE TABLE opseradb.messages (`message` String, `_topic` String, `_key` String,
     `_offset` UInt64, `_partition` UInt64, `_timestamp` DateTime, `_error` String, `_raw_message` String, `etl_date` Date DEFAULT toDate(now()), `etl_ts` DateTime DEFAULT now())
    ENGINE = MergeTree PARTITION BY toDate(_timestamp) ORDER BY (_topic, _timestamp) SETTINGS index_granularity = 8192
    */