resources:
  limits:
    cpu: 1000m
  requests:
    cpu: 250m

autoscaling:
  targetCPUUtilizationPercentage: 240

  enabled: true
  targetMemoryUtilizationPercentage: 120
ingress:
  hosts:
    - host: apigateway.workday-platform-private.opsera.io
      paths:
        - path: /
          pathType: ImplementationSpecific

replicaCount: 3
