resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 250m
    memory: 1Gi

autoscaling:
  targetCPUUtilizationPercentage: 240

ingress:
  hosts:
    - host: apigateway.honeywell-private.opsera.io
      paths:
        - path: /
          pathType: ImplementationSpecific
