apiVersion: v1
kind: Pod
metadata:
  name: mongosh-pod
spec:
  restartPolicy: Never
  containers:
    - name: mongo-init
      image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera/mongodb-lite-job:7.0.23-ubuntu2204
      command: [ "sleep", "infinity" ]
