ingress:
  hosts:
    - host: analytics-api.opsera-test.opsera.io
      paths: [/]

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

NODE_ENV: staging


clusterName: opsera-test-platform

datadogApm:
  enabled: true