{{- if .Values.ingress.enabled -}}
{{- $fullName := include "opsera-kubernetes-service-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $ingressHost := .Values.ingress.hosts -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "opsera-kubernetes-service-template.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- range .Values.ingress.secrets }}
  {{- if .certificate }}
  tls:
    - hosts:
        {{- range $ingressHost }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
