{{- if .Values.imageCredentials.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsera-kubernetes-service-template.fullname" . }}-docker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}