{{- if .Values.ingress.enabled }}
{{- $fullName := include "opsera-kubernetes-service-template.fullname" . -}}
{{- range .Values.ingress.secrets }}
{{- if .certificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
{{- end }}
{{- end }}
{{- end }}