resources:
  limits:
    cpu: 5000m
    memory: 5Gi
  requests:
    cpu: 400m
    memory: 4Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
