namespace: newrelic

serviceAccount:
  name: restart-newrelic-daemonset

role:
  name: restart-newrelic-daemonset

roleBinding:
  name: restart-newrelic-daemonset

cronjob:
  name: restart-newrelic-daemonset
  namespace: newrelic
  schedule: "0 6 * * *"
  serviceAccountName: restart-newrelic-daemonset
  image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/kubectl:1.33.2
  imagePullPolicy: Always
  deploymentToRestart: newrelic-bundle-newrelic-logging
  imagePullSecret: image-pull-secret 
