apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "tools-cleanup-cronjob.name" . }}
    chart: {{ template "tools-cleanup-cronjob.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "tools-cleanup-cronjob.fullname" . }}
data:
  excluded_tool_names.conf: |-
{{ .Values.excluded_tool_names | indent 4 }}
