apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "tools-cleanup-cronjob.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ quote .Values.cron.schedule }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit }}
      template:
        spec:
          serviceAccountName: {{ include "tools-cleanup-cronjob.serviceAccountName" . }}
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
          - name: kubectl
            imagePullPolicy: IfNotPresent
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            command:
            - "/bin/bash"
            - "-c"
            - |
              shutdown_tool() {
                namespaces=$1

                for namespace in ${namespaces[@]}; do
                  for tool_type in "deploy" "sts"; do
                    for resource in $(kubectl get $tool_type -n $namespace | tail -n+2 | awk '{print $1}'); do
                      echo "Shutting down ${resource} of type ${tool_type} in namespace ${namespace}"
                      # kubectl scale $tool_type -n $namespace $resource --replicas 0
                    done
                    echo "----------------------------------------"
                  done
                  echo "###########################################"
                done
                echo "###########################################"
              }

              get_tools_list() {
                pod_name=$1

                namespaces=$(kubectl get pod -A | grep $pod_name | awk '{print $1}' | sort | uniq)
                echo $namespaces
              }

              filter_tools() {
                tools=$1
                tools_filtered=()
                for tool in ${tools[@]}; do
                  if [[ ! $tool == qa* && ! $tool == FUTURE_CONDITION* ]]; then
                    tools_filtered+=("$tool")
                  fi
                done

                echo "${tools_filtered[@]}"
              }

              declare -A TOOL_CONFIGS=(
                ["Jenkins"]="opsera-jenkin-0"
                ["Sonarqube"]="opsera-sonarqube-sonarqube-lts-0"
                ["ArgoCD"]="opsera-argocd2-server"
                ["Nexus"]="opsera-nexus"
                ["Anchore"]="anchore"
              )

              for tool_name in "${!TOOL_CONFIGS[@]}"; do
                tools_list=$(get_tools_list "${TOOL_CONFIGS[$tool_name]}")
                tools_list_filtered=$(filter_tools "${tools_list[@]}")
                shutdown_tool "${tools_list_filtered[@]}"
              done
