apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Namespace }}-argocd
spec:
  commonName: {{ if gt (len .Values.server.ingress.hosts) 0 }}{{ (index .Values.server.ingress.hosts 0) | quote }}{{ else }}{{ "example.com" | quote }}{{ end }}
  dnsNames:
    {{- range .Values.server.ingress.hosts }}
    - {{ . }}
    {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ .Release.Namespace }}-argocd-tls
