---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mongodb-cert
  namespace: opsera-system
spec:
  secretName: mongodb-tls
  issuerRef:
    name: mongodb-cert-issuer
    kind: Issuer
  commonName: "*.mongodb-svc.opsera-system.svc.cluster.local"
  dnsNames:
  - "*.mongodb-svc.opsera-system.svc.cluster.local"
  - mongodb.litedev-private.opsera.io
