autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1

ingress:
  enabled: true
  hosts:
  - host: opsera-backstage-integrator-service.honeywell-sandbox-private.opsera.io
    paths: 
    - path: /protected/idp
  - host: api.honeywell-sandbox.opsera.io
    paths: 
    - path: /public/idp
