resources:
  requests:
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: 240

ingress:
  enabled: true
  hosts:
  - host: opsera-backstage-integrator-service.opsera-dev-private.opsera.io
    paths: 
    - path: /protected/idp
  - host: api.opsera-dev.opsera.io
    paths: 
    - path: /public/idp

NODE_ENV: testing