apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-logstash-integrator.fullname" . }}
  labels:
    {{- include "opsera-logstash-integrator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-logstash-integrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsera-logstash-integrator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-logstash-integrator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.DOCKER_ENV }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:          
          - name: "DOCKER_ENV"
            value: {{ .Values.DOCKER_ENV }}
          volumeMounts:
          - name: logstash-integrator-logs
            mountPath: /apps/OpsERA/logs/components/logstash-integrator
      volumes:
        - name: logstash-integrator-logs
          persistentVolumeClaim:
            claimName: logstash-integrator-logs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
