apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-node-sockets-service.fullname" . }}
  labels:
    {{- include "opsera-node-sockets-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-node-sockets-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{ if .Values.serviceCategory }}
        serviceCategory: {{ .Values.serviceCategory }}
        {{ end }}
        {{- include "opsera-node-sockets-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-node-sockets-service.serviceAccountName" . }}
      terminationGracePeriodSeconds: 900
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.service.port }}
            failureThreshold: 9
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.port }}
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:          
          - name: "DOCKER_ENV"
            value: {{ .Values.DOCKER_ENV }}
          - name: "NODE_ENV"
            value: {{default "production" .Values.NODE_ENV }}
          - name: "PORT"
            value: "{{ .Values.service.port }}"
          - name: "GIT_SHA"
            value: {{ .Values.image.tag }}
          {{- include "ms.extraSecretEnvironmentVars" .Values | nindent 10 }}
          volumeMounts:
          - name: microservices-efs
            mountPath: /apps/OpsERA/logs/components/
      volumes:
        - name: microservices-efs
          persistentVolumeClaim:
            claimName: microservices-efs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

