apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-fsx-ontap-helm
spec:
  version: 1
  backendName: fsx-ontap
  storageDriverName: ontap-nas
  managementLIF: {{ .Values.fsx_managementLIF }}
  dataLIF: {{ .Values.fsx_dataLIF }}
  svm: eks_fsx
  credentials:
    name: backend-fsx-ontap-secret
