kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-basic-xfs-helm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi
  storageClassName: basic-csi-xfs-helm
