resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

ingress:
  hosts:
    - host: app-v2.opsera-uat.opsera.io
      paths: [/]

NODE_ENV: staging
