resources:
  limits:
    memory: 2Gi
  requests:
    memory: 768Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 200


clusterName: opsera-test-platform

datadogApm:
  enabled: false