apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bamboo-shared-home
  namespace: opsera-bamboo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: bamboo-shared-home
