image:
  repository: 440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera/vault-lite-job
  tag: 1.17.2

serviceAccount:
  create: true

liteClusterId: litedevaza

customerId: tenant1

VAULT_URI: http://vault.litedev-private.opsera.io:8200

microservice_url: https://apigateway.opsera-dev-private.opsera.io/api/hashicorp-vault/platform/write
microservice_url_read: https://apigateway.opsera-dev-private.opsera.io/api/hashicorp-vault/platform/read
