apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-elk-elasticsearch.fullname" . }}
  labels:
    {{- include "opsera-elk-elasticsearch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-elk-elasticsearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsera-elk-elasticsearch.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-elk-elasticsearch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=524288"]
        securityContext:
          privileged: true
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777 /usr/share/elasticsearch/data; chmod -R 777 /usr/share/elasticsearch/logs']
        volumeMounts:
        - name: es01data
          mountPath: /usr/share/elasticsearch/data
        - name: log01
          mountPath: /usr/share/elasticsearch/logs
        # - name: config
        #   mountPath: /usr/share/elasticsearch/config
      imagePullSecrets:
       - name: imagepullsecret-patcher
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["sh", "-c", "cp -r /tmp/elasticsearch/config/* /usr/share/elasticsearch/config; ls /usr/share/elasticsearch/config" ]
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:          
          - name: "ELASTIC_PASSWORD"
            valueFrom:
              secretKeyRef:
                key:  password
                name: {{ include "opsera-elk-elasticsearch.fullname" . }}-auth
          volumeMounts:
          - name: es01data
            mountPath: /usr/share/elasticsearch/data
          - name: log01
            mountPath: /usr/share/elasticsearch/logs
          # - name: config
          #   mountPath: /usr/share/elasticsearch/config
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: {{ .Values.service.port }}
          #    scheme: HTTPS
          #    httpHeaders:
          #      - name: Authorization
          #        value: Basic {{ .Values.username_password }}
          #  initialDelaySeconds: 60
          #  timeoutSeconds: 10
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: {{ .Values.service.port }}
          #    scheme: HTTPS
          #    httpHeaders:
          #      - name: Authorization
          #        value: Basic {{ .Values.username_password }}
          #  initialDelaySeconds: 60
          #  timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: es01data
          persistentVolumeClaim:
            claimName: es01data
        - name: log01
          persistentVolumeClaim:
            claimName: log01
        # - name: config
        #   persistentVolumeClaim:
        #     claimName: config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
