apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-terraform-service.fullname" . }}
  labels:
    {{- include "opsera-terraform-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-terraform-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "datadogApm.selectorLabels" . | nindent 8 }}
        {{- include "opsera-terraform-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-terraform-service.serviceAccountName" . }}
      terminationGracePeriodSeconds: 7200
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- include "datadogApm.initContainer" . | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 40
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 40
          lifecycle:
            preStop:
              httpGet:
                path: /stopListener
                port: http
                scheme: HTTP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- include "datadogApm.environmentVars" . | nindent 10 }}
          - name: "DOCKER_ENV"
            value: {{ .Values.DOCKER_ENV }}
          {{- include "ms.extraSecretEnvironmentVars" .Values | nindent 10 }}
          volumeMounts:
          {{- include "datadogApm.volumeMounts" . | nindent 10 }}
          - name: microservices-efs
            mountPath: /apps/OpsERA/logs/components/
          - mountPath: "/apps/OpsERA/components/helmcharts"
            name: helm-charts
          lifecycle:
            postStart:
              exec:
                command: ["/bin/mkdir", "/apps/OpsERA/components/terraform"]
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
              - clone
              - -b
              - {{ .Values.HELM_GIT_BRANCH }}
              - --single-branch
              - https://{{ .Values.GIT_CREDENTIAL }}@github.com/OpseraEngineering/infra-helmcharts.git
              - /data
          volumeMounts:
          - mountPath: /data
            name: helm-charts
      volumes:
        {{- include "datadogApm.volumes" . | nindent 8 }}
        - name: helm-charts
          emptyDir: {}
        - name: microservices-efs
          persistentVolumeClaim:
            claimName: microservices-efs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
