apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-terraform-service.fullname" . }}
  labels:
    {{- include "opsera-terraform-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-terraform-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsera-terraform-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-terraform-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:          
          - name: "DOCKER_ENV"
            value: {{ .Values.DOCKER_ENV }}
          volumeMounts:
          - name: microservices-efs
            mountPath: /apps/OpsERA/logs/components/
          - mountPath: "/apps/OpsERA/components/helmcharts"
            name: helm-charts
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
              - clone
              - -b
              - {{ .Values.HELM_GIT_BRANCH }}
              - --single-branch
              - https://{{ .Values.GIT_CREDENTIAL }}@gitlab.com/opsera-repo/cloud-infrastructure/helmcharts.git
              - /data
          volumeMounts:
          - mountPath: /data
            name: helm-charts
      volumes:
        - name: helm-charts
          emptyDir: {}
        - name: microservices-efs
          persistentVolumeClaim:
            claimName: microservices-efs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
