apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eks-aws-auth.fullname" . }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "eks-aws-auth.serviceAccountName" . }}
      containers:
        - name: {{ include "eks-aws-auth.fullname" . }}
          image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              
              # Fetch the existing aws-auth ConfigMap
              kubectl get configmap aws-auth -n kube-system -o json > /tmp/aws-auth.json
              
              # Patch the ConfigMap with a new IAM user
              cat /tmp/aws-auth.json | jq '.data."mapUsers" |= (. + "\n- userarn: arn:aws:iam::{{ .Values.awsAccountId }}:user/{{ .Values.awsIamUser }}\n  username: {{ .Values.awsIamUser }}\n  groups:\n    - system:masters")' > /tmp/aws-auth-updated.json

              cat /tmp/aws-auth.json
              
              # Apply the updated ConfigMap
              kubectl apply -f /tmp/aws-auth-updated.json
              
          securityContext:
            runAsUser: 0
      restartPolicy: Never

