##########################################
# Kubernetes Integrator Volume
##########################################

k8sIntegratorName: k8s-integrator-shared-volume

k8sIntegratorVolumeName: opsera-shared-workspace

volumeSize: 1024Gi

storageClass: azurefile-csi

accessModes: [ReadWriteMany]

sharedWorkspaceBrowserName: shared-workspace-browser
