autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

ingress:
  hosts:
    - host: tools-management-service.opsera-test-private.opsera.io
      paths: [/]
