resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 4
  targetCPUUtilizationPercentage: 140
  targetMemoryUtilizationPercentage: 140

ingress:
  enabled: false
  hosts:
    - host: orchestration-service.opsera-uat-private.opsera.io
      paths:
        - path: /
          pathType: ImplementationSpecific

NODE_ENV: staging

