ingress:
  enabled: false
  hosts:
    - host: orchestration-service.honeywell-sandbox-private.opsera.io
      paths:
        - path: /
          pathType: ImplementationSpecific

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 140
  targetMemoryUtilizationPercentage: 60
