apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-elk-kibana.fullname" . }}
  labels:
    {{- include "opsera-elk-kibana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-elk-kibana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsera-elk-kibana.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-elk-kibana.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777 /usr/share/kibana/config; chmod -R 777 /usr/share/kibana/data']
        volumeMounts:
        - name: kibana-data
          mountPath: /usr/share/kibana/data
        - name: kibana-config
          mountPath: /usr/share/kibana/config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["sh", "-c", "ls -l /tmp/initialKibnaConfig/config; whoami; ls -l /usr/share/kibana/config/" ]
          command: ["sh", "-c", "cp -r /tmp/initialKibnaConfig/config/* /usr/share/kibana/config/; /usr/local/bin/kibana-docker" ]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:          
          - name: "ELASTICSEARCH_PASSWORD"
            valueFrom:
              secretKeyRef:
                key:  password
                name: {{ include "opsera-elk-kibana.fullname" . }}-auth
          - name: "ELASTICSEARCH_USERNAME"
            valueFrom:
              secretKeyRef:
                key:  username
                name: {{ include "opsera-elk-kibana.fullname" . }}-auth
          - name: "ELASTICSEARCH_HOSTS"
            value: {{ .Values.elasticSearchUrl }}
          - name: "SERVER_BASEPATH"
            value: "/kibana"
          - name: "SERVER_REWRITEBASEPATH"
            value: "true"
          volumeMounts:
          - name: kibana-data
            mountPath: /usr/share/kibana/data
          - name: kibana-config
            mountPath: /usr/share/kibana/config
          
          livenessProbe:
            httpGet:
              path: /kibana/login
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /kibana/login
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: kibana-data
          persistentVolumeClaim:
            claimName: kibana-data
        - name: kibana-config
          persistentVolumeClaim:
            claimName: kibana-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
