apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "opsera-artifact-management.labels" . | nindent 4 }}
  name: {{ include "opsera-artifact-management.fullname" . }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opsera-artifact-management.selectorLabels" . | nindent 6 }}
