apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-mongodb.fullname" . }}
  labels:
    {{- include "opsera-mongodb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-mongodb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsera-mongodb.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-mongodb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: host-sys
        hostPath:
          path: /sys
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data
      - name: mongodb-journal
        persistentVolumeClaim:
          claimName: mongodb-journal
      - name: mongodb-log
        persistentVolumeClaim:
          claimName: mongodb-log
      initContainers:
      - name: disable-thp
        image: busybox
        volumeMounts:
          - name: host-sys
            mountPath: /host-sys
        command: ["sh", "-c", "echo never >/host-sys/kernel/mm/transparent_hugepage/enabled; echo never >/host-sys/kernel/mm/transparent_hugepage/defrag"]
      containers:
        # - name: busybox
        #   image: busybox
        #   command: ["sh", "-c", "cat /sys/kernel/mm/transparent_hugepage/defrag; cat /sys/kernel/mm/transparent_hugepage/enabled"]
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "opsera-mongodb.fullname" . }}-auth
                key: mongodb-root-password
          - name: MONGODB_USERNAME
            value: {{ .Values.mongodbUsername | quote }}
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "opsera-mongodb.fullname" . }}-auth
                key: mongodb-password
          {{- if .Values.mongodbDatabase }}
          - name: MONGO_INITDB_DATABASE
            value: {{ .Values.mongodbDatabase | quote }}
          {{- end }}         
          ports:
            - name: http
              containerPort: 27017
          volumeMounts:
          - name: mongodb-data
            mountPath: /data
          - name: mongodb-journal
            mountPath: /data/db/journal
          - name: mongodb-log
            mountPath: /var/log/mongodb
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
