apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-log
  name: mongodb-log
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
