apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsera-mongodb.fullname" . }}-auth
data:
  mongodb-root-password: {{ .Values.mongodbRootPassword | b64enc }}
  mongodb-password: {{ .Values.mongodbPassword | b64enc }}