apiVersion: v1
kind: Secret
metadata:
  name: microservices-ms-env
data:
  {{- range $key, $value := .Values.extraSecretEnvironmentVars }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}