#ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: artifact-management.honeywell-sandbox-private.opsera.io
      paths:
        - path: /
          pathType: ImplementationSpecific
