ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: artifact-management.honeywell-private.opsera.io
      paths:
        - path: /
          pathType: ImplementationSpecific

OPSERA_ARTIFACT_SQS: honeywell-platform-artifact-sqs

accountid: 440953937617
nodeGroupIAM: honeywell-platform-eks-node-group