apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  #namespace: default
data:
  vault-agent-config.hcl: |
    # Comment this out if running as sidecar instead of initContainer
    # exit_after_auth = true
    pid_file = "/home/vault/pidfile"
    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "dev"
            }
        }
        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }

    cache {
        use_auto_auth_token = true
        # persist "kubernetes" {
        #     path = "/home/vault/agent-cache"
        # }
    }

    listener "tcp" {
        address = "127.0.0.1:8200"
        tls_disable = true
    }

    vault {
        address = "http://vault-active:8200"
    }