resources:
  limits:
    cpu: 1500m
    memory: 6Gi
  requests:
    cpu: "1"
    memory: 4Gi

autoscaling:
  enabled: true
  targetMemoryUtilizationPercentage: 105
  minReplicas: 6
  maxReplicas: 10
  targetCPUUtilizationPercentage: 105
