image:
  repository: public.ecr.aws/e7u7c9l1/aws-kubectl
  tag: 1.29.5

cron:
  schedule: "0 0 * * 0"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  backoffLimit: 4

serviceAccount:
  create: true
