---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.sharedWorkspaceBrowserName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.sharedWorkspaceBrowserName }}
  serviceName: {{ .Values.sharedWorkspaceBrowserName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.sharedWorkspaceBrowserName }}
    spec:
      volumes:
        - name: opsera-shared-workspace
          persistentVolumeClaim:
            claimName: {{ .Values.k8sIntegratorVolumeName }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Values.sharedWorkspaceBrowserName }}
          image: httpd:2.4.53
          ports:
            - containerPort: 80
              name: apt-repo-server
          volumeMounts:
            - name: opsera-shared-workspace
              mountPath: "/opsera/shared/workspace"
      nodeSelector:
        Name: tools-node
