apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name:  {{ include "mongodb-tenant.fullname" . }}
  name: {{ include "mongodb-tenant.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 4
  suspend: false
  template:
    metadata:
      labels:
        job-name: {{ include "mongodb-tenant.fullname" . }}
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          set -e

          mongosh "mongodb://mongodb-primary-0.mongodb-headless.opsera-system.svc.cluster.local:27017,mongodb-secondary-0.mongodb-headless.opsera-system.svc.cluster.local:27017,mongodb-secondary-1.mongodb-headless.opsera-system.svc.cluster.local:27017/?replicaSet=rs0" -u root -p {{ .Values.mongodbRootPassword }} --eval '
          try {
            use("{{ .Values.tenantName }}_{{ .Values.mongodbDatabase }}");
            db.createUser({
              user: "{{ .Values.tenantName }}_{{ .Values.mongodbUsername }}",
              pwd: "{{ .Values.mongodbPassword }}",
              roles: [{ role: "readWrite", db: "{{ .Values.tenantName}}_{{ .Values.mongodbDatabase }}" }]
            });
            print("User created successfully");
          } catch (e) {
            print("Error: " + e);
            quit(1);
          }
          '

          mongosh "mongodb://mongodb-primary-0.mongodb-headless.opsera-system.svc.cluster.local:27017,mongodb-secondary-0.mongodb-headless.opsera-system.svc.cluster.local:27017,mongodb-secondary-1.mongodb-headless.opsera-system.svc.cluster.local:27017/{{ .Values.tenantName}}_{{ .Values.mongodbDatabase }}?replicaSet=rs0" -u {{ .Values.tenantName }}_{{ .Values.mongodbUsername }} -p {{ .Values.mongodbPassword }}  --eval '
          try {
            db.dummy.insertOne({ init: true });
          } catch (e) {
            print("Error: " + e);
            quit(1);
          }
          '

          set -x
          sleep 30

        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: create-tenant-user
      restartPolicy: Never
