apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "imagepullsecret-patcher.fullname" . }}
  namespace: {{ include "imagepullsecret-patcher.fullname" . }}
  labels:
    {{- include "imagepullsecret-patcher.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }} 
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "imagepullsecret-patcher.fullname" . }}
  namespace: opsera
  labels:
    {{- include "imagepullsecret-patcher.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "imagepullsecret-patcher.fullname" . }}
  namespace: microservices
  labels:
    {{- include "imagepullsecret-patcher.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
