apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: imagepullsecret-patcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      serviceAccountName: webhook-server-sa
      containers:
        - name: webhook-server
          image: public.ecr.aws/e7u7c9l1/imagepullsecret-mutating-webhook:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: webhook-server-tls
              mountPath: /etc/webhook/tls
              readOnly: true
      volumes:
        - name: webhook-server-tls
          secret:
            secretName: webhook-server-tls
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: imagepullsecret-patcher
spec:
  ports:
    - port: 443
      targetPort: 8080
  selector:
    app: webhook-server
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0RENDQXB5Z0F3SUJBZ0lVWmdFYmNDSDZTZEpBeEZZcm42ZnhKcFhHTDRvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUI0WERUSTBNRFl4TXpFNE5Ua3pOMW9YRFRJMQpNRFl4TXpFNE5Ua3pOMW93TlRFek1ERUdBMVVFQXd3cWQyVmlhRzl2YXkxelpYSjJaWEl1YVcxaFoyVndkV3hzCmMyVmpjbVYwTFhCaGRHTm9aWEl1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQXRpcXROQVZSVkNiMTFZNmhjRWNISmJiQllaNmJEUGoxQnFBS3NOZndONlR2WXNKSnhwaVArOUtNVVYzZAptUjhMZDRBd2ZDOG5rMHhxVTUrNVRiU1ltZXNOYm1kQ1E3QjBZcUtMZWJCOVJaNThSbUFUSjREMWVBTHVLOUNQCm9FYmk4ekV5RVBsZkRrMCtJbDNIU2k0Q2ZxZHFtbXlXUkN6czhOWGprajFOVHJmYmlQWDZ2N2RkRnhsU3I1djAKNE5aMzMzOGpVQTRHMnhLdmNDVmk2ZFBQWU5xd21pQXhTaGl6TDRQcnhyZlpFaTRMVlFtM3pMdzVLQWJXYXZNZwpMRGRsWGtJL0VabFpZRUlqT280TVJ5ZGxkVGsxYlB5bTJkbFJWb0E2YXVhSnd3bno5Z0YzYThTRGd1L0R1dDhRCmduRklaRGtLSlZDNGhRbjJibnRNNzVqK1FRSURBUUFCbzRIWk1JSFdNQWtHQTFVZEV3UUNNQUF3Q3dZRFZSMFAKQkFRREFnWGdNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01DQmdnckJnRUZCUWNEQVRCZEJnTlZIUkVFVmpCVQpnaVozWldKb2IyOXJMWE5sY25abGNpNXBiV0ZuWlhCMWJHeHpaV055WlhRdGNHRjBZMmhsY29JcWQyVmlhRzl2CmF5MXpaWEoyWlhJdWFXMWhaMlZ3ZFd4c2MyVmpjbVYwTFhCaGRHTm9aWEl1YzNaak1CMEdBMVVkRGdRV0JCVGIKWjJKSTBTM05NcFRBQlZicDJVMFhwdTdmSERBZkJnTlZIU01FR0RBV2dCUnI5Vk1HdjVoU3kya016NW1pOUNoSQo0bk1xU2pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVU0aG85WnJ4bGNxVmQzbWdmVHdFaFVVMnUrZ1d3bHlaCkgybEtkdGZzYUI4TGluaVZFT2tBVDJVcHZaN2MwTjB0SjNNRWIxLzUwUkpkbFl4OXE4S08yOUNvRXh5YWh3Q3YKcXBla1JaaTNKWU5YdnliZVBKeENCZ3FmMjFKL3k1Q0prOWNIOG1LUEplVXJJcnZ4bkQ3ei8wYTZST1paSlcxawpxMmtVa3g0U2xWMVN6dzJzRkxodi8xZjVpeE5RVkhuVVlVWk5pQ3V3OGlCSkY1YkpSRUhWNE5MQnFtNWw1QlpFCkVBc05TSTIzYkdzQnhQWmo1M0Y1UEVaSnB5YktnZlBvNnVyTjJzTXBrREpWektFOVF5RVBPZk0zRFVnM2pEOGoKRU9sRlE0LzZzN1M3SXM0K2RGSFpBK0kyb0poaUNKYlhPVHZ4dkdZcWs5cE5pWUIrRFV1QmxnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzJLcTAwQlZGVUp2WFYKanFGd1J3Y2x0c0ZobnBzTStQVUdvQXF3MS9BM3BPOWl3a25HbUkvNzBveFJYZDJaSHd0M2dEQjhMeWVUVEdwVApuN2xOdEppWjZ3MXVaMEpEc0hSaW9vdDVzSDFGbm54R1lCTW5nUFY0QXU0cjBJK2dSdUx6TVRJUStWOE9UVDRpClhjZEtMZ0orcDJxYWJKWkVMT3p3MWVPU1BVMU90OXVJOWZxL3QxMFhHVkt2bS9UZzFuZmZmeU5RRGdiYkVxOXcKSldMcDA4OWcyckNhSURGS0dMTXZnK3ZHdDlrU0xndFZDYmZNdkRrb0J0WnE4eUFzTjJWZVFqOFJtVmxnUWlNNgpqZ3hISjJWMU9UVnMvS2JaMlZGV2dEcHE1b25EQ2ZQMkFYZHJ4SU9DNzhPNjN4Q0NjVWhrT1FvbFVMaUZDZlp1CmUwenZtUDVCQWdNQkFBRUNnZ0VBTmZNRG9xRmtpYWlVSzYvM0RicHJXbmI2WkgvRmFaMGRhOTNmN0ttM0FiTysKRmFCMm12TTV5Umw4NXVnR3BiOTA5T29vOGM1QlNUVmJVL0s4dlUrYjFoR3Z3NStmRjA3ZDJReE1oRGlKa1NHegpxbC92ckVaYjdEUHA5MTNuKzA2akRlVG03L0g2ZmREUWN2c1U5MW9TOFJHQjE4UUs2SnZwZkJYTU5OWWszQWZFCk8rdkkxV0lOeHMvS0hoQ1JjcnFSb2dOTUpFd2dBYk8xRWZscWRLcTltVmNBTzh4S2Rxd2tIcXFabGhPL2xFaEQKa05vYWVhNFpSbTc5TjNIM0NQVTBxZ3JyZ1hjd3BHZVJkcG9NSUp4TUphYlJuaysvWXJWSmxPeXdZVEs2RjNweQoxbTJqTU9uRmRjYS9CamNBcFc4b3djOEtuM0duWFBROTFXdXJrYWxmeFFLQmdRRDRQZmR2RlVZc0tva3pZc1NNCkpkYVBmMjY5dnFIakZBajBCek4yQnQ5SzhseDZaMVR2ZGRtVEtWazQ0RnhkOTFheTNjZ2RpeHpyV3NLTGJGRkoKcnFYbjl0UHFkMnViMmd2WXVOODFvUmIvUkxJb21Fb0swYkdPYi9HVE9jWWZVWDNXaVc3NFdKbk5Mc0UzTGgyNgpOYXJQZHlmUHIrV1FpT1BxV0ZrSjEvWElud0tCZ1FDNzNCVFc2VURWMmI4MTdDb25wZlkxWG8renhvVlhaQ3ZlCnd6KzJmYXNjNExWWnUvbEYwM2s5N1lUU05CRWwzMHFnUlBSempCam1uK0NZbjdQK2FycnNndUprb3N1c1RjVTAKTEpBT29XcG94b0k3ZDlaRDhkUlJzS3hyR2RHa2lxNE1TdEE2dnFKYUFhbjdQU0RZa2NLaHNpMTlBZjNLRFh3MApuQjgzSTFadEh3S0JnUURPZkRUQnVHOXJNMkoyVkxScVl0cnE5N08wcnNuWHFZV2MvaFJuRzJaRzMvdmVjTzhzClU5bkwxL3Y0SEYrWVpiRS9ETTExRFk3YmtkMzZ2UG1Na1hJODFZb0dJSmxveE9GUHZzOGp1Ny8yU3p6cUdXcVYKUDBFeTJwaVZ2dHUybDBGVjMzRm5yOE1XOGNvVHpRODdJWUxZR1NRTFZDTmVxdzd4a2RWV0k4VzB2d0tCZ0RDRgpUSUNocUZSVHRGWmFGQjAvZVZNWmhHWTdqUzhnT1ZDRS80ekQ4cEUzM0w4N2xNdWJMa0ozZVluTlZ1eUFPc2NnCmFENzczV2FidnFmTS8vRmpZYm82cC95MEs0VHFaVmZ2ZHBuQXlUb2NvNEIybUVuZVNTZDhTVncwUS9pS3RSK0oKcHpTMURqdlBHRGRDOTV2WU1md1BpRDQwYUhkcWVqMGdZZE9jOWZLakFvR0FCUHc5ZE5CbkE1N0ZWcVIzTnFSTApGZ0xPVERRMjg3cUR0YlRqa0FsbWh1RHRxN2U5eXJ3cEpHRW1FVlBKTFRRMEVTOXJGK2pJMVNGSS90Nk5oTFh2CmQ5YWJQWTlGT1RCeFNrQm83SS9XSG53SXpOVVJENHZOVFlneTNZV056MlVQU2NPZDYwQktacmhDWEFVbXpwRHEKUjJYVnFxN2l1WWVhU05PY3ZaK25yNXc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: webhook-server-tls
  namespace: imagepullsecret-patcher
type: kubernetes.io/tls
