apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-vnxt-insights-ui.fullname" . }}
  labels:
    {{- include "opsera-vnxt-insights-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-vnxt-insights-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{ if .Values.serviceCategory }}
        serviceCategory: {{ .Values.serviceCategory }}
        {{ end }}
        {{- include "opsera-vnxt-insights-ui.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-vnxt-insights-ui.serviceAccountName" . }}
      terminationGracePeriodSeconds: 300
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: configmap-volume
          configMap:
            defaultMode: 0777
            name: post-script-configmap
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env: 
          - name: "NODE_ENV"
            value: {{default "production" .Values.NODE_ENV }}
          - name: "GIT_SHA"
            value: {{ .Values.image.tag }}
          {{- include "ms.extraSecretEnvironmentVars" .Values | nindent 10 }}
          volumeMounts:
            - name: configmap-volume
              mountPath: /tmp/entrypoint.sh
              subPath: entrypoint.sh
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c 
                  - | 
                    set -x
                    set -e
                    echo starting;
                    while IFS='=' read -r -d '' n v; do
                        if [[ $n == REACT_ENV_OPSERA_* ]] 
                        then
                            n=${n#*REACT_ENV_}
                            v=${v%/}
                            echo $n
                            find /usr/local/apache2/htdocs -type f -name *.js | xargs sed -i  "s|ENV_${n}|${v}|g"
                        fi
                    done < <(env -0)
                # command: [ '/bin/sh', 'ls; while IFS="=" read -r -d "" n v; do find /usr/local/apache2/htdocs -type f | xargs sed -i  "s|ENV_${n}|${v}|g";done < <(env -0)']
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
