apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "opsera-jobengine-broker.labels" . | nindent 4 }}
  name: {{ include "opsera-jobengine-broker.fullname" . }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opsera-jobengine-broker.selectorLabels" . | nindent 6 }}
