resources:
  requests:
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 200

clusterName: opsera-test-platform

datadogApm:
  enabled: false

natsHubUrl: nats://nats-svc.nats-hub:4222/
