{{- if eq .Values.CLOUD_PROVIDER "AZURE" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: {{ .Values.jobEngineEfsVolumeClaim }}
  namespace: {{ .Values.jobEngineNamespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi
  storageClassName: azurefile-csi
{{- end }}