apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opsera-jobengine-core.fullname" . }}-configmap
  labels:
    {{- include "opsera-jobengine-core.labels" . | nindent 4 }}
data:
  config.yaml: |
    kubernetes:
      # nameSpace is the kubernetes namespace that jobengine will create its worker pods in
      nameSpace: {{ .Values.jobEngineNamespace }}
      # resourceProfiles 
      #
      # these are the pod resource profile specifications that will be used to create worker pods
      #   It is a list of profiles of the structure:
      #     name: SMALL
      #     memRequest: "1G"
      #     memLimit: "1G"
      #     cpuRequest: "500m"
      #     cpuLimit: "500m"
      #
      # the name property is an abstration that we use to simplify and standardize worker pod resources
      # the remaining fields directly correspond to kubernetes pod resource management: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#pod-level-resource-specification
      resourceProfiles:
        - name: SMALL
          {{- toYaml .Values.resourceProfiles.small | nindent 10 }}
        - name: MEDIUM
          {{- toYaml .Values.resourceProfiles.medium | nindent 10 }}
        - name: LARGE
          {{- toYaml .Values.resourceProfiles.large | nindent 10 }}
        - name: XLARGE
          {{- toYaml .Values.resourceProfiles.xlarge | nindent 10 }}
        - name: 2XLARGE
          {{- toYaml .Values.resourceProfiles.twoxlarge | nindent 10 }}
        - name: MICRO
          {{- toYaml .Values.resourceProfiles.micro | nindent 10 }}
      # defaultContainerImages
      #
      # Jobengine has 2 default container images. If a job is submitted that does not directly specifiy an image to use then the "common" container image will be used.
      # if a job is submitted that directly indicates it will require a container image to be built then the "dockerBuild" container image will be used.
      defaultContainerImages:
        common: {{ .Values.jobEngineContainerImage | default "440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera-pipeline/ubuntu:latest" }}
        # common: ubuntu:latest
        # dockerBuild: 440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera-pipeline/buildah:alpine
        dockerBuild: buildah/buildah
      # containerImageMaps
      #
      # Opsera Jobs are allowed to specify the use of a specific opsera maintained container image.
      # If these specified images need to be overridden to point to a customer maintained image then the containerImageMap
      # values provide the ability to map the "source" opsera image to a customer maintained "target" image
      containerImageMaps:
        - source: golang:1.20.7-bullseye
          target: golang:1.23.4-bullseye
      # nodeSelectors custom node selectors can be specified here to target pod creation with in a kubernetes cluster.
      nodeSelectors:
        - key: Name
          value: tools-node
      #   - key: kubernetes.io/os
      #     value: linux
