apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: {{ .Values.jobEngineEfsVolumeClaim }}
  namespace: {{ .Values.jobEngineNamespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: {{ .Values.jobEngineEfsVolumeClaim }}-jobengine
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: {{ .Values.jobEngineEfsVolumeClaim }}-jobengine
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .Values.jobEngineEfsVolumeClaim }}
    namespace: {{ .Values.jobEngineNamespace }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ include "opsera-jobengine-core.efsVolumeId" . }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem
