{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "eks-upgrade.namespace" . }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "eks-upgrade.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
{{- end }}
