autoscaling:
  minReplicas: 3

  enabled: true
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
resources:
  limits:
    cpu: 750m
    memory: 2Gi
  requests:
    cpu: 750m
    memory: 2Gi

