apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jiradc-shared-home
  namespace: opsera-jira-dc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: jiradc-shared-home
