apiVersion: v1
kind: PersistentVolume
metadata:
  name: jiradc-shared-home
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jiradc-shared-home
    namespace: opsera-jira-dc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-042d04f8a7d492177
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem
