database:
  type:
  url: jdbc:postgresql://
  credentials:
    secretName: jira-db-creds
    usernameSecretKey: username
    passwordSecretKey: password
volumes:
  localHome:
    persistentVolumeClaim:
      create: true
      storageClassName: gp3
      resources:
        requests:
          storage: 1Gi
  sharedHome:
    customVolume:
      persistentVolumeClaim:
        claimName: jiradc-shared-home
