apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsera-node-data-migration-file-service.fullname" . }}
  labels:
    {{- include "opsera-node-data-migration-file-service.labels" . | nindent 4 }}
  annotations:
    {{- include "opsera-node-data-migration-file-service.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5019
      protocol: TCP
      name: http
  selector:
    {{- include "opsera-node-data-migration-file-service.selectorLabels" . | nindent 4 }}
