autoscaling:
  minReplicas: 1

  enabled: true
  targetCPUUtilizationPercentage: 140
  targetMemoryUtilizationPercentage: 240
NODE_ENV: staging

extraSecretEnvironmentVarsExtended:
  - secretName: microservices-ms-env
    envName: WANDB_API_KEY
    secretKey: OPSERA_WANDB_API_KEY