resources:
  requests:
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 240

ingress:
  enabled: true
  hosts:
  - host: agent-supervisor-service.opsera-dev-private.opsera.io
    paths: 
    - path: /

NODE_ENV: testing

extraSecretEnvironmentVarsExtended:
  - secretName: microservices-ms-env
    envName: WANDB_API_KEY
    secretKey: OPSERA_WANDB_API_KEY