{{- if .Values.opseraConfig }}
apiVersion: v1
data:
  {{- range $configName, $config := $.Values.opseraConfig }}
  {{- with $config }}
  {{ printf "%s" $configName }}: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
kind: ConfigMap
metadata:
  name: cluster-agent-opsera-config
{{- end }}