{{- if .Values.opseraConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-opsera-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
type: Opaque
data:
  mongo-password: {{ default "null" .Values.mongodbPassword | b64enc }}
  redisdb-password: {{ default "null" .Values.redisdbPassword | b64enc }}
{{- end }}