kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "newrelic-tools-health-check.fullname" . }}
  namespace: opsera
subjects:
- kind: ServiceAccount
  name: {{ include "newrelic-tools-health-check.fullname" . }}
  namespace: newrelic-tools-health-check
roleRef:
  kind: ClusterRole
  name: {{ include "newrelic-tools-health-check.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
