apiVersion: v1
data:
  NR_API_KEY: NmFhMjZhMzMyZDcwNmZjYjViOGZlMzAxNTUwYjFjNTVGRkZGTlJBTA==
  #DD_APP_KEY: Y2M1MWJhMGRmZTc1MzQwNTE4NTBjMzA0MGNiMzJmYjQ4ZGMxMDcwMA==
kind: Secret
metadata:
  name: {{ include "newrelic-tools-health-check.fullname" . }}
  namespace: newrelic-tools-health-check
type: Opaque
