apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "newrelic-tools-health-check.fullname" . }}
  namespace: newrelic-tools-health-check
  labels:
    {{- include "newrelic-tools-health-check.labels" . | nindent 4 }}
