autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

  targetCPUUtilizationPercentage: 140
  targetMemoryUtilizationPercentage: 240
clusterName: opsera-test-platform

datadogApm:
  enabled: false