apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opsera-jenkin.fullname" . }}-azurefile
  labels:
    {{- include "opsera-jenkin.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 500Gi
