apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkin-server-key
data:
  server.key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAwMaGjVVGLJtZrG33/UdkOWmIzvkaW3XmWU+mmTMDRJkwr409
    k+HXfbu0pkSDsWdM23ByF3CSegq34O/AdzY6ctVKvg/cpdo6auPKkJ+qqTN3ARvZ
    18nTWoqTmQvQEpb0vyWnw7AhNHt72LUe2nxm7ojaiETvk20E+9Cg1ZXnBUQqg45z
    9N1lmPVl63AJ+dU4d57aYLlEe9/xCTO/Mq6v/PQzEAKm+FjdLFe0SXegWz1U8msn
    mgToC9yG4uWwbQ8QTfeg7ZZFCpt2uKA1L5KBltf/En5JH0rQYMiF7NUzZbo6n1cA
    iLFC311ggs8Mm3hHoFYdLFp5mhY48pNsznBwzwIDAQABAoIBAQCedRE4r3WFSRUG
    5UXJDZvWjWcFKkF+GIWFuDErEIGJK5qXUrPhEOy+z0IIwZy2gEDux5kgp0nfw1uu
    K6S62PpmVeigHg2yzpTiM+fXxUbU2hbh9HC2LZHrhKkaTll0Tl1TmbIy6l4A89ez
    I/3+fe9l91waUv/S4PQNwUnTBurkqdqsNbXmhpk8OVaYybCijQjegMN6axVd5T6h
    HkP/o+h70GXo7lS+QssijcftmXsWMmh0FVfJwxW2o+lesHxkr83Rxpu6due50Kbj
    ANeFK52sNdKiQXll0f9gtsgQT6frKgQLz2pxnC5kw1oQRNqq21N8r742Wd6O6xUF
    AekAJtxxAoGBAPQSKOfbrXaa1FN3EQOjF3tG9ZIwqbdTyZq3C/rRvz7MbJIO+gWz
    kFF9Etn1Y3Zm7d7yP+MUpJJ4JcJ3NpR1iI5sm6ONxo5TIcIWB/z9lhccNCk1YE1/
    J3PDKUFtRcdVE99TZNoHZek0D8A8PktUrxORWLeqmhY7o0tewkVZUL6DAoGBAMoy
    jVAf7tbd4M8nUWXzmkzNnjgQDpBfuQ8TEhUUpO1nRU8NFYdnjXNMr3OUaDeaqHw2
    1F6w1epNdZ/TdA2x/ZXI0Slw3mM3qx/9EWNdL/uLgzs/E/xogxCk2qz3DOg547rk
    cinYgN6Lj1Nn+nog01fGoJUHOIwobYekh+AeEvLFAoGBANJNy31tJlxqMMXydHCj
    2RnaHMNotvRGeBKd4u6uSJG951c7HGhJPvNYSCQScy+UpSZTqoTqRpwGdtLHkfn+
    BDpkjv8wrIP6Ub5A6YUupGMpZDCV03MzOzVeVnAPze5h+ouV+fJ8KW319BR6VFro
    jyrXNJCdqcO6g4vwDIlg2lgtAoGANmL6l76/I5Ryz8Wno2Cu9FGqaTIIeNUGlgNv
    LbRr2F+ayPSgAdfcuFK8Lr6QecRj5WVqIj42i9th9CeQY86ogw2NFTSC3PUwVl5f
    uvZp3aNdHSaOXapO9r8hAr1A/4Xyt2aTPqY5o6KuXqTtPsRtlIKc1vkmQKzvKTkc
    QzBTsHECgYB10p/QYaoteu6muiLBT6YC2piuEjFkORJf0qpD4CItwTZWLfWMnz8C
    zjDvHGiwE6L3lM+ceEQX7eLlfWGSWL1PsNbfEt6ez17sdSqwJP4JmHi0Tj7KyYdc
    AuRryx788VxaTRmlyDE6QrKXjShlSzaDog0Yr2yPslWVDYQxT8+69A==
    -----END RSA PRIVATE KEY-----
