apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -e
    echo starting;
    sleep 120
    cd vault/
    status=$(vault status | grep Sealed | awk '{print $2}')
    if $status; then 
      vault operator init > keys.txt
      root_token=$(cat keys.txt | grep Initial | awk '{print $4}')
      vault login $root_token
      vault secrets enable transit
      vault write -f transit/keys/opsera
      vault secrets enable kv

      tee dev-policy.hcl <<EOF
      # List, create, update, and delete key/value secrets
      path "secret/*"
      {
        capabilities = ["create", "read", "update", "delete", "list", "sudo"]
      }
      # List, create, update, and delete key/value transit
      path "transit/*"
      {
        capabilities = ["create", "read", "update", "delete", "list", "sudo"]
      }
      # List, create, update, and delete key/value kv
      path "kv/*"
      {
        capabilities = ["create", "read", "update", "delete", "list", "sudo"]
      }
      EOF

      vault policy write developer dev-policy.hcl

      vault auth enable kubernetes
      vault write auth/kubernetes/config kubernetes_host="{{ .Values.K8S_HOST }}"
      vault write auth/kubernetes/role/dev \
        bound_service_account_names=vault \
        bound_service_account_namespaces=opsera \
        policies=developer \
        ttl=1h

      KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      echo $KUBE_TOKEN

      kube_token=$(echo $KUBE_TOKEN | base64 | tr -d '\n')
      vault_token=$(printf $root_token | base64)
      vault_uri=$(printf {{ .Values.VAULT_URI }} | base64)
      vault_role=$(printf "dev" | base64)

      if [ -z != $vault_token ] ; then 
        curl --location --request POST {{ .Values.microservice_url }} \
        --header 'accept: application/json' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "customerId": "{{ .Values.customer_id }}",
            "data": {
              "VAULT_TOKEN": "'$vault_token'",
              "VAULT_KEY": "b3BzZXJh",
              "VAULT_URI": "'$vault_uri'",
              "KUBE_TOKEN": "'$kube_token'",
              "VAULT_ROLE": "'$vault_role'"
          }
        }' -k
      else 
        echo 'It is replica vault'
      fi
      
    else 
      echo 'Unsealed'
    fi
    
    echo done;
