autoscaling:
  enabled: true

  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 4Gi
