apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-delete-archive
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-delete-archive
            image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera-pipeline/jenkins-agent:latest
            imagePullPolicy: Always
            command: ["/home/cronjobs/delete-artifacts/01.sh"]
            args:
            - admin
            - {{  .Values.password }}
            - {{ .Values.JENKINS_UI_URL }}
          restartPolicy: Never
