apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-delete-archive
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-delete-archive
            image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera-pipeline/jenkins-agent:test
            imagePullPolicy: Always
            command: ["/home/cronjobs/delete-artifacts/01.sh"]
            args:
            - admin
            - 11f50e9a4090c7bc756384e103e19b21bc
            - https://jenkins-olge.ldapowner.opsera.io
          restartPolicy: Never
