apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "opsera-jenkin"
  labels:
    {{- include "opsera-jenkin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-jenkin.selectorLabels" . | nindent 6 }}
  serviceName: "opsera-jenkin"
  template:
    metadata:
      labels:
        {{- include "opsera-jenkin.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-jenkin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3
        command: ['sh', '-c', 'chmod -R 777  /temp/jenkins_home']
        volumeMounts:
        - name: my-disk-claim-1
          mountPath: /temp/jenkins_home
      - name: copy-data
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ['sh', '-c', 'cp -r /var/jenkins_home/* /temp/jenkins_home/']
        volumeMounts:
        - name: my-disk-claim-1
          mountPath: /temp/jenkins_home
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777  /var/jenkins_home; rm -rf /var/jenkins_home/plugins; rm -rf /var/jenkins_home/init.groovy.d; mv -f /temp/jenkins_home/plugins /var/jenkins_home/plugins; mv -f /temp/jenkins_home/init.groovy.d /var/jenkins_home/init.groovy.d; mv -vn /temp/jenkins_home/* /var/jenkins_home/;']
        volumeMounts:
        - name: opsera-jenkins-master-efs
          mountPath: /var/jenkins_home
        - name: my-disk-claim-1
          mountPath: /temp/jenkins_home
      containers:
        - name: jenkins
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: JENKINS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key:  password
                name: {{ include "opsera-jenkin.fullname" . }}-auth
          - name: JENKINS_UI_URL
            value: {{ .Values.JENKINS_UI_URL }}
          - name: JENKINS_OPTS
            value: --prefix=/
          - name: KUBERNETES_URL
            value: {{ .Values.KUBERNETES_URL }}
          - name: KUBERNETES_NAMESPACE
            value: {{ .Values.KUBERNETES_NAMESPACE }}
          - name: JENKINS_WORKSPACE_EFS
            value: {{ include "opsera-jenkin.fullname" . }}-{{ .Values.KUBERNETES_NAMESPACE }}-agentefs-pvc
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
          - mountPath: "/var/jenkins_home"
            name: opsera-jenkins-master-efs
          - mountPath: /home/jenkins/agent
            name: opsera-jenkins-agent-efs
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: server-key
            mountPath: /var/jenkins_home/sfdx/key/server.key
            subPath: server.key
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: my-disk-claim-1
        persistentVolumeClaim:
          claimName: my-disk-claim-1
      - name: opsera-jenkins-master-efs
        persistentVolumeClaim:
          claimName: {{ include "opsera-jenkin.fullname" . }}-{{ .Values.KUBERNETES_NAMESPACE }}-masterefs-pvc
      - name: opsera-jenkins-agent-efs
        persistentVolumeClaim:
          claimName: {{ include "opsera-jenkin.fullname" . }}-{{ .Values.KUBERNETES_NAMESPACE }}-agentefs-pvc
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: server-key
        configMap:
          defaultMode: 0777
          name: jenkin-server-key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
