apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opsera-jenkin.fullname" . }}-efs
  labels:
    {{- include "opsera-jenkin.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "opsera-jenkin.fullname" . }}-{{ .Values.KUBERNETES_NAMESPACE }}
  labels:
    {{- include "opsera-jenkin.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.EFS_VOLUME_ID }}
