apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "opsera-jenkin.fullname" . }}-{{ .Values.KUBERNETES_NAMESPACE }}-masterefs-pv
  labels:
    {{- include "opsera-jenkin.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     name: {{ include "opsera-jenkin.fullname" . }}-{{ .Values.KUBERNETES_NAMESPACE }}-masterefs-pvc
     namespace: {{ .Values.KUBERNETES_NAMESPACE }}
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.EFS_VOLUME_ID }}::{{ .Values.EFS_JENK_MASTER_AP }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opsera-jenkin.fullname" . }}-{{ .Values.KUBERNETES_NAMESPACE }}-masterefs-pvc
  labels:
    {{- include "opsera-jenkin.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi