# Default values for opsera-clickhouse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

OPSERA_PASSWORD: default
CUSTOMER_NAME: prod
CUSTOMER_ID: jcs3rincsdni2
KAFKA_BROKER_LIST: aebc67922dca34d76b34d1b83b951fea-626fe2b9cd27f673.elb.us-east-2.amazonaws.com:9094
KAFKA_TOPIC_LIST: 'opsera.azure.terraform.integrator.aks.request\n,
opsera.azure.terraform.integrator.aks.response\n,
opsera.cache.refresh.alert\n,
opsera.cache.refresh.monitor\n,
opsera.cache.refresh.notification.policy\n,
opsera.consolelog.jenkins\n,
opsera.consolelog.octopus\n,
opsera.deactivate.user\n,
opsera.delete.tools.terraform\n,
opsera.git.merge.task.request\n,
opsera.git.task.log\n,
opsera.git.task.status\n,
opsera.incident.manage\n,
opsera.instance.stop\n,
opsera.invoker.terraform\n,
opsera.logs\n,
opsera.logs.monitor\n,
opsera.logs.transformed\n,
opsera.notification.email\n,
opsera.notification.gchat\n,
opsera.notification.jira\n,
opsera.notification.logstash\n,
opsera.notification.node.jira\n,
opsera.notification.node.slack\n,
opsera.notification.response.slack\n,
opsera.notification.s3\n,
opsera.notification.ses.email\n,
opsera.notification.slack\n,
opsera.notification.teams\n,
opsera.pipeline.anchore.log\n,
opsera.pipeline.anchore.report\n,
opsera.pipeline.anchore.request\n,
opsera.pipeline.anchore.response\n,
opsera.pipeline.anchore.status\n,
opsera.pipeline.ansible.console.log\n,
opsera.pipeline.ansible.log\n,
opsera.pipeline.ansible.request\n,
opsera.pipeline.ansible.response\n,
opsera.pipeline.ansible.status\n,
opsera.pipeline.apigee.request\n,
opsera.pipeline.argo.notification\n,
opsera.pipeline.argo.request\n,
opsera.pipeline.aws.ebs.log\n,
opsera.pipeline.aws.ebs.request\n,
opsera.pipeline.aws.ebs.response\n,
opsera.pipeline.aws.ebs.status\n,
opsera.pipeline.aws.ecs.log\n,
opsera.pipeline.aws.ecs.request\n,
opsera.pipeline.aws.ecs.response\n,
opsera.pipeline.aws.ecs.status\n,
opsera.pipeline.aws.lambda.console.log\n,
opsera.pipeline.aws.lambda.log\n,
opsera.pipeline.aws.lambda.request\n,
opsera.pipeline.aws.lambda.response\n,
opsera.pipeline.aws.lambda.status\n,
opsera.pipeline.aws.s3.request\n,
opsera.pipeline.awss3.log\n,
opsera.pipeline.awss3.request\n,
opsera.pipeline.awss3.response\n,
opsera.pipeline.awss3.status\n,
opsera.pipeline.azure.cli.request\n,
opsera.pipeline.azure.function.request\n,
opsera.pipeline.azure.storage.request\n,
opsera.pipeline.azure.webapps.request\n,
opsera.pipeline.azurestorage.log\n,
opsera.pipeline.azurestorage.request\n,
opsera.pipeline.azurestorage.response\n,
opsera.pipeline.azurestorage.status\n,
opsera.pipeline.blackduck.request\n,
opsera.pipeline.boomi.request\n,
opsera.pipeline.buildkite.console.log\n,
opsera.pipeline.buildkite.log\n,
opsera.pipeline.buildkite.request\n,
opsera.pipeline.buildkite.response\n,
opsera.pipeline.buildkite.status\n,
opsera.pipeline.console.log\n,
opsera.pipeline.coverity.console.log\n,
opsera.pipeline.coverity.log\n,
opsera.pipeline.coverity.request\n,
opsera.pipeline.coverity.response\n,
opsera.pipeline.coverity.status\n,
opsera.pipeline.dockercli.request\n,
opsera.pipeline.external.rest.api.integration.request\n,
opsera.pipeline.flyway.console.log\n,
opsera.pipeline.flyway.log\n,
opsera.pipeline.flyway.request\n,
opsera.pipeline.flyway.response\n,
opsera.pipeline.flyway.status\n,
opsera.pipeline.fortify.request\n,
opsera.pipeline.gitscraper.request\n,
opsera.pipeline.informatica.console.log\n,
opsera.pipeline.informatica.idq.request\n,
opsera.pipeline.informatica.log\n,
opsera.pipeline.informatica.request\n,
opsera.pipeline.informatica.response\n,
opsera.pipeline.informatica.status\n,
opsera.pipeline.jenkins.console.log\n,
opsera.pipeline.jenkins.log\n,
opsera.pipeline.jenkins.request\n,
opsera.pipeline.jenkins.response\n,
opsera.pipeline.jenkins.status\n,
opsera.pipeline.jenkins.summary.log\n,
opsera.pipeline.jfrog.log\n,
opsera.pipeline.jfrog.request\n,
opsera.pipeline.jfrog.response\n,
opsera.pipeline.jfrog.status\n,
opsera.pipeline.jirarequest\n,
opsera.pipeline.kafka.con\n,
opsera.pipeline.kafka.connect.log\n,
opsera.pipeline.kafka.connect.request\n,
opsera.pipeline.kafka.connect.response\n,
opsera.pipeline.kafka.connect.status\n,
opsera.pipeline.liquibase.request\n,
opsera.pipeline.log\n,
opsera.pipeline.mongodb.realm.console.log\n,
opsera.pipeline.mongodb.realm.log\n,
opsera.pipeline.mongodb.realm.request\n,
opsera.pipeline.mongodb.realm.response\n,
opsera.pipeline.mongodb.realm.status\n,
opsera.pipeline.nexus.log\n,
opsera.pipeline.nexus.request\n,
opsera.pipeline.nexus.response\n,
opsera.pipeline.nexus.status\n,
opsera.pipeline.octopus.console.log\n,
opsera.pipeline.octopus.log\n,
opsera.pipeline.octopus.request\n,
opsera.pipeline.octopus.response\n,
opsera.pipeline.octopus.status\n,
opsera.pipeline.packer.console.log\n,
opsera.pipeline.packer.log\n,
opsera.pipeline.packer.request\n,
opsera.pipeline.packer.response\n,
opsera.pipeline.packer.status\n,
opsera.pipeline.response\n,
opsera.pipeline.run.status\n,
opsera.pipeline.salesforce.request\n,
opsera.pipeline.sapcpq.request\n,
opsera.pipeline.sentinel.console.log\n,
opsera.pipeline.sentinel.log\n,
opsera.pipeline.sentinel.request\n,
opsera.pipeline.sentinel.response\n,
opsera.pipeline.sentinel.status\n,
opsera.pipeline.snaplogic.request\n,
opsera.pipeline.status\n,
opsera.pipeline.summary.log\n,
opsera.pipeline.terraform.console.log\n,
opsera.pipeline.terraform.log\n,
opsera.pipeline.terraform.request\n,
opsera.pipeline.terraform.response\n,
opsera.pipeline.terraform.status\n,
opsera.pipeline.twistlock.console.log\n,
opsera.pipeline.twistlock.log\n,
opsera.pipeline.twistlock.report\n,
opsera.pipeline.twistlock.request\n,
opsera.pipeline.twistlock.response\n,
opsera.pipeline.twistlock.status\n,
opsera.step.cancellation.jenkins\n,
opsera.step.cancellation.response\n,
opsera.step.cancellation.sfdc\n,
opsera.task.analytics.summary\n,
opsera.task.console.log\n,
opsera.task.gitscraper.request\n,
opsera.task.log\n,
opsera.task.response\n,
opsera.task.snaplogic.request\n,
opsera.task.status\n,
opsera.task.summary.log\n,
opsera.terraform.pipeline.consolelog\n,
opsera.terraform.pipeline.request\n,
opsera.terraform.pipeline.response\n,
opsera.terraform.retry\n,
opsera.tool.connectivity.status\n,
opsera.tools.spinup.completed\n,
opsera.toolspinup.completed\n,
opsera.topiccreation.test\n,
opsera.webhook.gitlab'

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1M
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: clickhouse.devqaaccc-private.opsera.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
