apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: analyzer
  name: analyzer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: analyzer
    spec:
      containers:
      - args:
        - anchore-manager
        - service
        - start
        - analyzer
        env:
        - name: ANCHORE_DB_HOST
          value: db
        - name: ANCHORE_DB_PASSWORD
          value: mysecretpassword
        - name: ANCHORE_ENDPOINT_HOSTNAME
          value: analyzer
        image: anchore/anchore-engine:v0.7.2
        name: analyzer
        resources: {}
        volumeMounts:
        - mountPath: /analysis-scratch
          name: analyzer-claim0
      restartPolicy: Always
      volumes:
      - name: analyzer-claim0
        persistentVolumeClaim:
          claimName: analyzer-claim0
status: {}
