autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10

CONTROL_PLANE_ENV: prod
CONTROL_PLANE_ENV_SQS: opsera-prod

accountid: 440953937617
nodeGroupIAM: opsera-prod-eks-node-group
