autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

ingress:
  hosts:
    - host: jira-connect.opsera-test.opsera.io
      paths:
        - path: /
          pathType: ImplementationSpecific

clusterName: opsera-test-platform

datadogApm:
  enabled: true