opseraConfig:
  mongo-d:
    cluster_check: true
    init_config:
    instances:
      - hosts:
        - mongodb-primary-0.mongodb-headless.opsera.svc.cluster.local:27017
        username: datadog
        password: "%%env_DATADOG_MONGO_PASSWORD%%"
        database: admin
        replica_check: true
        custom_queries:
        - metric_prefix: opsera.mongo.collection.documents.count
          query: {"count": "useractivities"}
          count_type: gauge
          database: opseradb
          tags:
          - replicaname:primary-0
          - cluster_name:opsera-dev-platform
          - kube_namespace:opsera
          - collection:useractivities
        tags:
          - replicaname:primary-0
          - cluster_name:opsera-dev-platform
          - kube_namespace:opsera
      - hosts:
        - mongodb-secondary-0.mongodb-headless.opsera.svc.cluster.local:27017
        username: datadog
        password: "%%env_DATADOG_MONGO_PASSWORD%%"
        database: admin
        replica_check: true
        tags:
          - replicaname:secondary-0
          - cluster_name:opsera-dev-platform
          - kube_namespace:opsera
      - hosts:
        - mongodb-secondary-1.mongodb-headless.opsera.svc.cluster.local:27017
        username: datadog
        password: "%%env_DATADOG_MONGO_PASSWORD%%"
        database: admin
        replica_check: true
        tags:
          - replicaname:secondary-1
          - cluster_name:opsera-dev-platform
          - kube_namespace:opsera
      - hosts:
        - mongodb.devqaaccc-private.opsera.io:27017
        username: datadog
        password: "%%env_DATADOG_MONGO_PASSWORD%%"
        database: admin
        replica_check: true
        tags:
          - replicaname:primary-0
          - cluster_name:opsera-dev-dataplane
          - kube_namespace:opsera
  redisdb-d:
    cluster_check: true
    init_config:
    instances:
      - host: opsera-redis.opsera.svc.cluster.local
        port: 6379
        tags:
          - cluster_name:opsera-dev-platform
          - kube_namespace:opsera