opseraConfig:
  mongo-d:
    cluster_check: true
    init_config:
    instances:
      - hosts:
        - mongodb.opsera.svc.cluster.local:27017
        username: datadog
        password: "%%env_DATADOG_MONGO_PASSWORD%%"
        database: admin
        replica_check: true
        custom_queries:
        - metric_prefix: opsera.mongo.collection.documents.count
          query: {"count": "useractivities"}
          count_type: gauge
          database: opsera
          tags:
          - replicaname:primary-0
          - cluster_name:opsera-prod-platform
          - kube_namespace:opsera
          - collection:useractivities
        tags:
          - replicaname:primary-0
          - cluster_name:opsera-prod-platform
          - kube_namespace:opsera