autoscaling:
  minReplicas: 2

  enabled: true
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
NODE_ENV: staging

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi