export const AUTH_CONFIG = {
  IDLE_TIMEOUT_MINUTES: 30,
  ABSOLUTE_TIMEOUT_HOURS: 12,
  MAX_FAILED_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 15,
  AUTH_RATE_LIMIT_PER_MINUTE: 10,
  IDLE_FLUSH_INTERVAL_SECONDS: 60,
} as const;
