resources:
  limits:
    cpu: 1500m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 3
  targetCPUUtilizationPercentage: 180
  targetMemoryUtilizationPercentage: 120
