autoscaling:
  minReplicas: 1

  enabled: true
  targetCPUUtilizationPercentage: 140
  targetMemoryUtilizationPercentage: 120
ingress:
  hosts:
    - host: agent.opsera-uat.opsera.io

NODE_ENV: staging