apiVersion: v1
kind: ConfigMap
metadata:
  name: ri-post-script-configmap
data:
  entrypoint.sh: |-
    #!/bin/sh
    set -x
    set -e
    echo starting;
    while IFS='=' read -r -d '' n v; do
        if [[ $n == REACT_ENV_OPSERA_* ]] 
        then
            n=${n#*REACT_ENV_}
            v=${v%/}
            echo $n
            find /usr/local/apache2/htdocs -type f | xargs sed -i  "s|ENV_${n}|${v}|g"
        fi
    done < <(env -0)