apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-fsx-ontap-nas
  namespace: {{ .Values.tridentNameSpace }}
spec:
  version: 1
  backendName: fsx-ontap
  storageDriverName: ontap-nas
  managementLIF: {{ .Values.managementLIF }}
  dataLIF: {{ .Values.dataLIF }}
  svm: {{ .Values.svm }}
  credentials:
    name: backend-tbc-fsx-ontap-nas-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-fsx-ontap-nas-secret
  namespace: {{ .Values.tridentNameSpace }}
type: Opaque
stringData:
  username: fsxadmin
  password: {{ .Values.fsxadminPassword }}

