resources:
  limits:
    cpu: 500m
    memory: 3Gi
  requests:
    cpu: 500m
    memory: 3Gi

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

nodeGroupIAM: honeywell-platform-eks-node-group
accountid: "440953937617"
