{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opsera-saas-deploy-service.serviceAccountName" . }}
  labels:
    {{- include "opsera-saas-deploy-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.accountid }}:role/{{ .Values.nodeGroupIAM }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}

