autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5

ingress:
  hosts:
    - host: api-integrator-service.opsera-dev-private.opsera.io
      paths:
        - path: /
          pathType: ImplementationSpecific

NODE_ENV: staging
