autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

  targetCPUUtilizationPercentage: 350
  targetMemoryUtilizationPercentage: 200
clusterName: opsera-test-platform

datadogApm:
  enabled: false