image:
  repository: 440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera-cron/newrelic-tools-health-check
  #repository: 440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera-pipeline/ubuntu:latest
  tag: "v2.2"

nrMetricName: opsera.tool.healthcheck.status

cron: "*/5 * * * *"

nodeSelector: tools-node
