ingress:
  hosts:
    - host: app.workday.opsera.io
      paths: [/]

resources:
  limits:
    cpu: 3300m
    memory: 7Gi
  requests:
    cpu: 1500m
    memory: 7Gi

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 4
