ingress:
  hosts:
    - host: api.honeywell.opsera.io
      paths: [/]

resources:
  limits:
    memory: 6Gi
  requests:
    memory: 6Gi

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 4
