apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-config-service.fullname" . }}
  labels:
    {{- include "opsera-config-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-config-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{ if .Values.serviceCategory }}
        serviceCategory: {{ .Values.serviceCategory }}
        {{ end }}
        {{- include "datadogApm.selectorLabels" . | nindent 8 }}
        {{- include "opsera-config-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-config-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- include "datadogApm.initContainer" . | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 40
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 40
          lifecycle:
            preStop:
              httpGet:
                path: /stopListener
                port: http
                scheme: HTTP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- include "datadogApm.environmentVars" . | nindent 10 }}
          - name: "DOCKER_ENV"
            value: {{ .Values.DOCKER_ENV }}
          - name: "JAVA_OPTS"
            value: "-XX:MaxRAMPercentage=60.0"
          {{- include "ms.extraSecretEnvironmentVars" .Values | nindent 10 }}
          volumeMounts:
          {{- include "datadogApm.volumeMounts" . | nindent 10 }}
          - name: microservices-efs
            mountPath: /apps/OpsERA/logs/components/
      volumes:
        {{- include "datadogApm.volumes" . | nindent 8 }}
        - name: microservices-efs
          persistentVolumeClaim:
            claimName: microservices-efs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
