ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: true
  hosts:
  - host: redis-pvc.devqaaccc-private.opsera.io
    paths:
    - path: /
      pathType: ImplementationSpecific
Platform: dataplane
REDIS_PASSWORD: # configure the redis password
