apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-autounseal-config
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -e
    echo starting;
    sleep 60
    cd vault/

    #### Check vault status
    status=$(vault status | grep Sealed | awk '{print $2}')

    #### If not unsealed, setup vault
    if $status; then 

      ### Generate root token and login
      vault operator init > keys.txt
      root_token=$(cat keys.txt | grep Initial | awk '{print $4}')
      vault login $root_token

      ### Enable Secrets engine
      vault secrets enable transit
      vault write -f transit/keys/opsera

      ### Enable KV Engine
      vault secrets enable kv

    ### Create admin policy
    tee admin-policy.hcl <<EOF
        path "secret/*"
        {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
        }
        path "transit/*"
        {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
        }
        path "kv/*"
        {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
        }
    EOF
      vault policy write admin admin-policy.hcl

      ### Enable Kubernetes Auth login
      vault auth enable kubernetes
      vault write auth/kubernetes/config kubernetes_host="{{ .Values.K8S_HOST }}" disable_iss_validation=true
      vault write auth/kubernetes/role/dev \
        bound_service_account_names=vault \
        bound_service_account_namespaces=opsera-system \
        policies=admin \
        ttl=1h

      KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      echo $KUBE_TOKEN

      kube_token=$(echo $KUBE_TOKEN | base64 | tr -d '\n')
      vault_token=$(printf $root_token | base64)
      vault_uri=$(printf {{ .Values.VAULT_URI }} | base64 | tr -d '\n')
      vault_role=$(printf "dev" | base64)

      if [ -z != $vault_token ] ; then 
        curl --location --request POST {{ .Values.microservice_url }} \
        --header 'accept: application/json' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "customerId": "{{ .Values.customer_id }}",
            "data": {
              "VAULT_TOKEN": "'$vault_token'",
              "VAULT_KEY": "b3BzZXJh",
              "VAULT_URI": "'$vault_uri'",
              "KUBE_TOKEN": "'$kube_token'",
              "VAULT_ROLE": "'$vault_role'"
          }
        }' -k
      else 
        echo 'It is replica vault'
        echo 'It is replica vault' > /vault/replica_vault.log
      fi
    else 
      echo 'Unsealed'
      echo 'Unsealed' > /vault/unsealed.log
    fi
