apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "opsera-infra-service.fullname" .) }}
  labels:
    {{- include "opsera-infra-service.labels" . | nindent 4 }}
  annotations:
    {{- include "opsera-infra-service.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- if .Values.service.selector }}
    {{- toYaml .Values.service.selector | nindent 4 }}
    {{- else }}
    {{- include "opsera-infra-service.selectorLabels" . | nindent 4 }}
    {{- end }}
  ports:
    - port: {{ .Values.service.port | default 5000 }}
      targetPort: {{ .Values.service.targetPort | default 5000 }}
      protocol: TCP
      name: http

