resources:
  limits:
    memory: 2Gi
  requests:
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetMemoryUtilizationPercentage: 60

clusterName: opsera-test-platform

datadogApm:
  enabled: false