resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 512Mi

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 300
  targetMemoryUtilizationPercentage: 120

CONTROL_PLANE_ENV: honsandbox
CONTROL_PLANE_ENV_SQS: honeywell-sandbox

accountid: 440953937617
nodeGroupIAM: honeywell-sandbox-eks-node-group
