ingress:
  hosts:
    - host: app.workday.opsera.io
      paths: [/]

resources:
  limits:
    cpu: 3300m
    memory: 4800Mi
  requests:
    cpu: 1500m
    memory: 4800Mi

autoscaling:
  enabled: true
  minReplicas: 6
  maxReplicas: 6

CONTROL_PLANE_ENV: workdayprod
CONTROL_PLANE_ENV_SQS: workday-platform

nodeGroupIAM: workday-platform-eks-node-group
accountid: "440953937617"
