resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 350
  targetMemoryUtilizationPercentage: 140

ingress:
  hosts:
    - host: design-system-demo.opsera-test-private.opsera.io
      paths:
        - path: /
          pathType: ImplementationSpecific

NODE_ENV: testing