resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 300
  targetMemoryUtilizationPercentage: 120

ingress:
  hosts:
    - host: portal.freetrial.opsera.io
      paths: 
        - path: /
          pathType: ImplementationSpecific
NODE_ENV: testing