apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sonarqube-conf
  name: sonarqube-conf
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
