apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-sonarqube.fullname" . }}
  labels:
    {{- include "opsera-sonarqube.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-sonarqube.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsera-sonarqube.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-sonarqube.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3
        command: ['sh', '-c', 'chmod -R 777  /temp/sonarqube/data']
        volumeMounts:
        - name: sonarqube-temp-data
          mountPath: /temp/sonarqube/data
      - name: copy-data
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        command: ['sh', '-c', 'cp -r /opt/sonarqube/data/* /temp/sonarqube/data']
        volumeMounts:
        - name: sonarqube-temp-data
          mountPath: /temp/sonarqube/data
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777  /opt/sonarqube/data; mv -vn /temp/sonarqube/data/* /opt/sonarqube/data/']
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        - name: sonarqube-temp-data
          mountPath: /temp/sonarqube/data
      # conf data copy
      - name: take-conf-dir-ownership
        image: alpine:3
        command: ['sh', '-c', 'chmod -R 777  /temp/sonarqube/conf']
        volumeMounts:
        - name: sonarqube-temp-data
          mountPath: /temp/sonarqube/conf
      - name: copy-conf
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        command: ['sh', '-c', 'cp -r /opt/sonarqube/conf/* /temp/sonarqube/conf']
        volumeMounts:
        - name: sonarqube-temp-data
          mountPath: /temp/sonarqube/conf
      - name: volume-permissions-conf
        image: busybox
        command: ['sh', '-c', 'chmod -R 777  /opt/sonarqube/conf; mv -vn /temp/sonarqube/conf/* /opt/sonarqube/conf/']
        volumeMounts:
        - name: sonarqube-conf
          mountPath: /opt/sonarqube/conf
        - name: sonarqube-temp-data
          mountPath: /temp/sonarqube/conf
      # extensions data copy
      - name: take-extensions-dir-ownership
        image: alpine:3
        command: ['sh', '-c', 'chmod -R 777  /temp/sonarqube/extensions']
        volumeMounts:
        - name: sonarqube-temp-data
          mountPath: /temp/sonarqube/extensions
      - name: copy-extensions
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        command: ['sh', '-c', 'cp -r /opt/sonarqube/extensions/* /temp/sonarqube/extensions']
        volumeMounts:
        - name: sonarqube-temp-data
          mountPath: /temp/sonarqube/extensions
      - name: volume-permissions-extensions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777  /opt/sonarqube/extensions; mv -vn /temp/sonarqube/extensions/* /opt/sonarqube/extensions/']
        volumeMounts:
        - name: sonarqube-extensions
          mountPath: /opt/sonarqube/extensions
        - name: sonarqube-temp-data
          mountPath: /temp/sonarqube/extensions
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "SONARQUBE_PASSWORD"
            value: {{ .Values.SONARQUBE_PASSWORD }}
          - name: "SONARQUBE_BASE_URL"
            value: {{ .Values.SONARQUBE_BASE_URL }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /sessions/new
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /sessions/new
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: sonarqube-data
            mountPath: /opt/sonarqube/data
          - name: sonarqube-extensions
            mountPath: /opt/sonarqube/extensions
          - name: sonarqube-conf
            mountPath: /opt/sonarqube/conf
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions
        - name: sonarqube-conf
          persistentVolumeClaim:
            claimName: sonarqube-conf
        - name: sonarqube-temp-data
          persistentVolumeClaim:
            claimName: sonarqube-temp-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
