apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "consul.fullname" . }}-backup
spec:
  schedule: "0 */4 * * *"
  # schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: consul-backup
            image: alpine:3
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - sleep 15;apk add --no-cache curl;apk add --no-cache sudo;apk add python3;apk add py3-pip;pip3 install awscli;mkdir consul-backup;cd consul-backup;curl http://consul-consul-server.{{ .Values.NAMESPACES }}.svc.cluster.local:8500/v1/snapshot -o snapshot-$(date +"%Y_%m_%d_%I_%M_%p").tgz; ls -l; aws s3 cp --recursive /consul-backup/ s3://{{ .Values.BACKUP_BUCKET_NAME }}/consul-backup/;
          restartPolicy: Never