autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

ingress:
  hosts:
    - host: aws-marketplace-registration-service.opsera-dev-private.opsera.io
      paths: [/]
