resources:
  limits:
    cpu: 500m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 300
  targetMemoryUtilizationPercentage: 120