kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    {{- include "k8s-integrator-volume.labels" . | nindent 4 }}
  name: {{ .Values.k8sIntegratorVolumeName }}
  namespace: {{ .Values.k8sIntegratorNamespace }}
spec:
  accessModes:
    {{- range .Values.accessModes }}
      - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumeSize | quote }}
  storageClassName: {{ .Values.storageClass }}