apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "k8s-integrator-volume.labels" . | nindent 4 }}
  name: {{ include "k8s-integrator-volume.fullname" . }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-integrator-volume.fullname" . }}
  labels:
    {{- include "k8s-integrator-volume.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-integrator-volume.fullname" . }}
  namespace: {{ .Release.Namespace }}
