apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsera-nexus.fullname" . }}
  labels:
    {{- include "opsera-nexus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsera-nexus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsera-nexus.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "opsera-nexus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3
        command: ['sh', '-c', 'chmod -R 777  /temp/nexus-data']
        volumeMounts:
        - name: temp-data
          mountPath: /temp/nexus-data
      - name: copy-data
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ['sh', '-c', 'cp -r /nexus-data/* /temp/nexus-data/']
        volumeMounts:
        - name: temp-data
          mountPath: /temp/nexus-data
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777  /nexus-data; mv -vn /temp/nexus-data/* /nexus-data/']
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        - name: temp-data
          mountPath: /temp/nexus-data
      hostNetwork: true
      containers:
        - name: nginx-sidecar
          image: {{ .Values.sidecarImage }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          # image: "brndnmtthws/nginx-echo-headers"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # ports:
          #   - name: http
          #     containerPort: {{ .Values.service.port }}
          #     protocol: TCP
          volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
          env:
          # - name: NEXUS_CONTEXT
          #   value: /
          - name: NEXUS_PASSWORD
            value: {{ .Values.NEXUS_PASSWORD }}
          - name: INSTALL4J_ADD_VM_PARAMS
            value: "-Dnexus.datastore.enabled=true -Dnexus.scripts.allowCreation=true -Dnexus.security.randompassword=false"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data
        - name: temp-data
          persistentVolumeClaim:
            claimName: temp-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
