ingress:
  hosts:
    - host: vnext-insights-api.workday-platform.opsera.io
      paths:
        - path: /vnext
          pathType: ImplementationSpecific
        - path: /nx
          pathType: ImplementationSpecific
