ingress:
  hosts:
    - host: portal.honeywell-sandbox.opsera.io
      paths:
        - path: /vnext
          pathType: ImplementationSpecific
        - path: /nx
          pathType: ImplementationSpecific          
