resources:
  limits:
    memory: 1536Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 200

clusterName: opsera-test-platform

datadogApm:
  enabled: false