apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "health-agent.fullname" . }}
  labels:
    {{- include "health-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "health-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "health-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "health-agent.serviceAccountName" . }}
      containers:
        - name: health-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: CLUSTER_ID
              value: {{ .Values.env.CLUSTER_ID | quote }}
            - name: HTTP_PORT
              value: {{ .Values.env.HTTP_PORT | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
